name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
    paths:
      - '**/*'

jobs:
  build-Core:
    if: ${{ github.repository == 'EZPZ-OS/EZPZOS.Core' }}
    runs-on: ubuntu-latest
    outputs:
      Core_build_status: ${{ steps.install_build_core.outcome }}
    steps:
      - name: Checkout Core repository
        uses: actions/checkout@v2
        with:
          repository: EZPZ-OS/EZPZOS.Core
          ref: main

      - name: Install and build Core
        run: |
          npm install
          npm run build



 
